ArenaWeb/Controllers/Authentification/AuthentificationController.cs
using System.Threading.Tasks;
using ArenaWeb.Data;
using ArenaWeb.Extensions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace ArenaWeb.Controllers.Authentification
{
	public class AuthenticationController : Controller
	{
		#region Fields

		private readonly AppDbContext context;

		#endregion

		#region Constructor

		public AuthenticationController(AppDbContext context)
		{
			this.context = context;
		}

		#endregion

		#region Properties



		#endregion

		#region Methods

		[HttpGet("~/signin")]
		public async Task<IActionResult> SignIn() => View("SignIn", await HttpContext.GetExternalProvidersAsync());

		[HttpPost("~/signin")]
		public async Task<IActionResult> SignIn([FromForm] string provider)
		{
			// Note: the "provider" parameter corresponds to the external
			// authentication provider choosen by the user agent.
			if (string.IsNullOrWhiteSpace(provider))
			{
				return BadRequest();
			}

			if (!await HttpContext.IsProviderSupportedAsync(provider))
			{
				return BadRequest();
			}

			// Instruct the middleware corresponding to the requested external identity
			// provider to redirect the user agent to its own authorization endpoint.
			// Note: the authenticationScheme parameter must match the value configured in Startup.cs
			return Challenge(new AuthenticationProperties { RedirectUri = "/" }, provider);
		}

		[HttpGet("~/signout")]
		[HttpPost("~/signout")]
		public IActionResult SignOut()
		{
			// Instruct the cookies middleware to delete the local cookie created
			// when the user agent is redirected from the external identity provider
			// after a successful authentication flow (e.g Google or Facebook).
			return SignOut(new AuthenticationProperties { RedirectUri = "/" },
				CookieAuthenticationDefaults.AuthenticationScheme);
		}

		#endregion
	}
}

ArenaWeb/Controllers/Home/HomeController.cs
using ArenaWeb.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ArenaWeb.Controllers.Home
{
	public class HomeController : Controller
	{
		#region Fields

		private readonly AppDbContext db;

		#endregion

		#region Constructor

		public HomeController(AppDbContext db)
		{
			this.db = db;
		}

		#endregion

		#region Properties



		#endregion

		#region Methods

		#region Web-API

		[HttpGet("~/")]
		public async Task<IActionResult> Index()
		{
			var userId = User.Claims.Where(c => c.Type.Contains("nameidentifier")).FirstOrDefault()?.Value;

			if (null == userId)
			{
				return View();
			}

			var dbUser = await db.Twitchuser.Where(u => u.Twitchuser_Id == userId).FirstOrDefaultAsync();

			if (null == dbUser || true)
			{
				return View("~/Views/Register/Index.cshtml");
			}
			else
			{
				return View();
			}
		}
	}

	#endregion

	#endregion
}

ArenaWeb/Controllers/Privacy/AboutController.cs
using ArenaWeb.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArenaWeb.Controllers.Privacy
{
	public class AboutController : Controller
	{
		#region Fields

		private readonly AppDbContext db;

		#endregion

		#region Constructor

		public AboutController(AppDbContext db)
		{
			this.db = db;
		}

		#endregion

		#region Properties



		#endregion

		#region Methods

		#region Web-API

		public async Task<IActionResult> Index()
		{
			return View();
		}

		#endregion

		#endregion
	}
}

ArenaWeb/Controllers/Privacy/PrivacyController.cs
using ArenaWeb.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArenaWeb.Controllers.Privacy
{
	public class PrivacyController : Controller
	{
		#region Fields

		private readonly AppDbContext db;

		#endregion

		#region Constructor

		public PrivacyController(AppDbContext db)
		{
			this.db = db;
		}

		#endregion

		#region Properties



		#endregion

		#region Methods

		#region Web-API

		public async Task<IActionResult> Index()
		{
			return View();
		}

		#endregion

		#endregion
	}
}

ArenaWeb/Controllers/User/CatchedPokemonsController.cs
using ArenaWeb.Data;
using ArenaWeb.Transfer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ArenaWeb.Controllers.User
{
	public class CatchedPokemonsController : Controller
	{
		private readonly AppDbContext context;

		public CatchedPokemonsController(AppDbContext context)
		{
			this.context = context;
		}

		// GET: CatchedPokemons
		public async Task<IActionResult> Index()
		{
			var userId = User.Claims.Where(c => c.Type.Contains("nameidentifier")).FirstOrDefault()?.Value;
			var catchedPokemonQuery = context.Twitchuser.Where(tu => tu.Twitchuser_Id == userId);
			var catchedPokemonResult = await catchedPokemonQuery.SelectMany(u => u.CatchedPokemon.Select(c => new TransferDexElement()
			{
				Id = c.SdPokemon.SdPokemon_Id,
				Number = c.SdPokemon.Number.ToString(),
				Name = c.SdPokemon.Name,
				Amount = c.Pokemon_AmountCatched
			})).ToListAsync();

			var pokedexQuery = context.SdPokemon.Select(s => new TransferDexElement()
			{
				Id = s.SdPokemon_Id,
				Number = s.Number.ToString(),
				Name = s.Name
			});

			var pokedexResult = await pokedexQuery.ToListAsync();

			foreach (var entry in pokedexResult)
			{
				var catchedElement = catchedPokemonResult.FirstOrDefault(e => e.Id == entry.Id);

				if (null != catchedElement)
				{
					entry.Amount = catchedElement.Amount;
				}
				else
				{
					entry.Amount = 0;
				}
			}

			return View(pokedexResult);
		}

		[HttpPost]
		public async Task<IActionResult> AddToTeam(decimal id)
		{
			return null;
		}

		[HttpPost]
		public async Task<IActionResult> RemoveFromTeam(decimal id)
		{
			return null;
		}
	}
}

ArenaWeb/Controllers/User/TeamController.cs
using ArenaWeb.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArenaWeb.Controllers.User
{
	public class TeamController : Controller
	{
		#region Fields

		private readonly AppDbContext db;

		#endregion

		#region Constructor

		public TeamController(AppDbContext db)
		{
			this.db = db;
		}

		#endregion

		#region Properties



		#endregion

		#region Methods

		#region Web-API

		public async Task<IActionResult> Index()
		{
			return View();
		}

		#endregion

		#endregion
	}
}

ArenaWeb/Controllers/User/UserController.cs
using ArenaWeb.Data;
using ArenaWeb.Transfer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ArenaWeb.Controllers.User
{
	public class UserController : Controller
	{
		#region Fields

		private readonly AppDbContext db;

		#endregion

		#region Constructor

		public UserController(AppDbContext db)
		{
			this.db = db;
		}

		#endregion

		#region Properties



		#endregion

		#region Methods

		#region Web-API

		public async Task<IActionResult> Index()
		{
			var userId = User.Claims.Where(c => c.Type.Contains("nameidentifier")).FirstOrDefault()?.Value;
			var query = db.Twitchuser.Where(u => u.Twitchuser_Id == userId);
			var queryResult = await query.Select(r => new TransferUserElement()
			{
				UserName = r.DisplayName,
				RegisterDt = DateTime.Now,
				TotalPokemonCatched = r.CatchedPokemon.Sum(c => c.Pokemon_AmountCatched),
				TotalUniquePokemonCatched = r.CatchedPokemon.Count(),
				TotalAchievementsUnlocked = r.Achievements.Count(),
				TotalAchievementsDone = r.Achievements.Where(a => a.LastFight != null).Count(),
				StarterPokemon = "Platzhalter"
			}).FirstOrDefaultAsync();

			return View(queryResult);
		}

		#endregion

		#endregion
	}
}

ArenaWeb/Views/About/Index.cshtml
@{
    ViewData["Title"] = "Über";
}
<h1>Nope.</h1>

Nope.
<br />
<br />

ArenaWeb/Views/Authentication/ProcessLogin.cshtml
@{
    ViewData["Title"] = "ProcessLogin";
}

<h1>ProcessLogin</h1>

YOYOOYoOOY

ArenaWeb/Views/Authentication/SignIn.cshtml
@using Microsoft.AspNetCore.Authentication
@model AuthenticationScheme[]

<div class="jumbotron">
    <h1>Login</h1>
    <p class="lead text-left">Du kannst dich über einen dieser Provider authentifizieren:</p>

    @foreach (var scheme in Model.OrderBy(p => p.DisplayName))
    {
<form action="/signin" method="post">
    <input type="hidden" name="Provider" value="@scheme.Name" />
    <input type="hidden" name="ReturnUrl" value="@ViewBag.ReturnUrl" />

    <button class="btn btn-lg btn-success m-1" type="submit">@scheme.DisplayName</button>
</form>}
</div>

ArenaWeb/Views/CatchedPokemons/Create.cshtml
@model ArenaWeb.Data.Models.Entities.CatchedPokemon

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CatchedPokemon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pokemon_AmountCatched" class="control-label"></label>
                <input asp-for="Pokemon_AmountCatched" class="form-control" />
                <span asp-validation-for="Pokemon_AmountCatched" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pokemon_AmountOnFightingTeam" class="control-label"></label>
                <input asp-for="Pokemon_AmountOnFightingTeam" class="form-control" />
                <span asp-validation-for="Pokemon_AmountOnFightingTeam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SdPokemon_Id" class="control-label"></label>
                <select asp-for="SdPokemon_Id" class ="form-control" asp-items="ViewBag.SdPokemon_Id"></select>
            </div>
            <div class="form-group">
                <label asp-for="Twitchuser_Id" class="control-label"></label>
                <select asp-for="Twitchuser_Id" class ="form-control" asp-items="ViewBag.Twitchuser_Id"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ArenaWeb/Views/CatchedPokemons/Delete.cshtml
@model ArenaWeb.Data.Models.Entities.CatchedPokemon

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CatchedPokemon</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pokemon_AmountCatched)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pokemon_AmountCatched)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pokemon_AmountOnFightingTeam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pokemon_AmountOnFightingTeam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SdPokemon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SdPokemon.SdPokemon_Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Twitchuser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Twitchuser.Twitchuser_Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CatchedPokemon_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ArenaWeb/Views/CatchedPokemons/Details.cshtml
@model ArenaWeb.Data.Models.Entities.CatchedPokemon

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CatchedPokemon</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pokemon_AmountCatched)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pokemon_AmountCatched)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pokemon_AmountOnFightingTeam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pokemon_AmountOnFightingTeam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SdPokemon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SdPokemon.SdPokemon_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Twitchuser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Twitchuser.Twitchuser_Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CatchedPokemon_Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ArenaWeb/Views/CatchedPokemons/Edit.cshtml
@model ArenaWeb.Data.Models.Entities.CatchedPokemon

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CatchedPokemon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CatchedPokemon_Id" />
            <div class="form-group">
                <label asp-for="Pokemon_AmountCatched" class="control-label"></label>
                <input asp-for="Pokemon_AmountCatched" class="form-control" />
                <span asp-validation-for="Pokemon_AmountCatched" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pokemon_AmountOnFightingTeam" class="control-label"></label>
                <input asp-for="Pokemon_AmountOnFightingTeam" class="form-control" />
                <span asp-validation-for="Pokemon_AmountOnFightingTeam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SdPokemon_Id" class="control-label"></label>
                <select asp-for="SdPokemon_Id" class="form-control" asp-items="ViewBag.SdPokemon_Id"></select>
                <span asp-validation-for="SdPokemon_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Twitchuser_Id" class="control-label"></label>
                <select asp-for="Twitchuser_Id" class="form-control" asp-items="ViewBag.Twitchuser_Id"></select>
                <span asp-validation-for="Twitchuser_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ArenaWeb/Views/CatchedPokemons/Index.cshtml
@model IEnumerable<ArenaWeb.Transfer.TransferDexElement>

@{
    ViewData["Title"] = "Pokedex";
}
<h1>Mein Pokedex</h1>

An dieser Stelle findest du eine Gesamtübersicht über alle existierenden Pokemon und welche du davon bereits gefangen hast.
<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Name
            </th>
            <th>
                Gefangene Anzahl
            </th>
            <th>
                Team-Aktionen
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.Amount > 0)
            {
                <tr style="background-color:#2ECD00">
                    <td>
                        @Html.DisplayFor(modelItem => item.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        <form asp-controller="CatchedPokemons" asp-action="AddToTeam" style="display: inline; width: 50px">
                            <button type="submit" value="99">efewfewefw</button>
                        </form>

                        <form asp-controller="CatchedPokemons" asp-action="RemoveFromTeam" style="display: inline; width: 50px">
                            <button type="submit" value="99">efewfewefw</button>
                        </form>


                    </td>
                </tr>
            }
            else
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Number)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

ArenaWeb/Views/Home/Index.cshtml
<div class="jumbotron">

    <!-- User is authenticated-->
    @if (User?.Identity?.IsAuthenticated ?? false)
    {
<h1>Hallo @User.Claims.FirstOrDefault(c => c.Type.Contains("displayname"))?.Value,</h1>

                <p>
                    willkommen zurück zum Web-Interface der PokeArena.
                </p> <!-- anonymous user--> }
            else
            {
<h1>Hallo anonymer Benutzer,</h1>
                <p>
                    Es freut uns sehr dass du den Weg in das Web-Interface der PokeArena gefunden hast.

                    Wenn du bereits registriert bist, kannst du <a href="/signin?returnUrl=%2F">hier</a> klicken um dich mit deinem Twitch-Account einzuloggen.
                    Ansonsten kannst du dich <a href="/register">hier</a> neu registrieren und dir dein Starter-Pokemon auswählen!
                </p>}
</div>

ArenaWeb/Views/Privacy/Index.cshtml
@{
    ViewData["Title"] = "Impressum";
}
<h1>Gibts nicht.</h1>

~_~
<br />
<br />

ArenaWeb/Views/Register/Index.cshtml
@{
    ViewData["Title"] = "Registrierung";
}
Yallah yallah!

ArenaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>PokeArena</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha256-fTuUgtT7O2rqoImwjrhDgbXTKUwyxxujIMRIK7TbuNU=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <!-- Account -->
                <a class="navbar-brand" href="/">Home</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <!-- Account -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">@User.Claims.FirstOrDefault(c => c.Type.Contains("displayname"))?.Value</a>
                            </li>

                            <!-- My Pokedex -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CatchedPokemons" asp-action="Index">Mein Pokedex</a>
                            </li>

                            <!-- Team -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Index">Team</a>
                            </li>

                            <!-- Settings -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Authentification/SignIn">Einstellungen</a>
                            </li>

                            <!-- Logout -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="signout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <!-- Login -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="signin">Login</a>
                            </li>
                        }

                        <!-- About -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">Über</a>
                        </li>

                        <!-- Impressum -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Privacy" asp-action="Index">Impressum</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ArenaWeb - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ArenaWeb/Views/Team/Index.cshtml
@model IEnumerable<ArenaWeb.Transfer.TransferFightingTeam>

@{
    ViewData["Title"] = "Team";
}
<h1>Mein Team</h1>

Hier kannst du die Pokemon festlegen, welche in einem Team-Kampf gegeneinander antreten.
<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Name
            </th>
            <th>
                Aktion
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < 6; i++)
        {
            <tr>
                <td>
                    @(i + 1)
                </td>
                <td>
                    TBD
                </td>
                <td>
                    TBD
                </td>
            </tr>
        }
    </tbody>
</table>

ArenaWeb/Views/User/Account.cshtml
@{
    ViewData["Title"] = "Account";
}

    <h1>Hallo @User.Identity.Name</h1>
Über dich:

Deine Statistiken:

ArenaWeb/Views/User/Index.cshtml
@model ArenaWeb.Transfer.TransferUserElement

@{
    ViewData["Title"] = "Account-Informationen";
}

<h1>Über dich</h1>

Hier findest du einige interessante Statistiken über deine Trainer-Karriere:
<br />

<b>@Html.DisplayFor(i => i.UserName)</b>, du hast dich am <b>@Html.DisplayFor(i => i.RegisterDt)</b> registriert und dabei <b>@Html.DisplayFor(i => i.StarterPokemon)</b> als Starter-Pokemon gewählt.
<br />

In deinen <b>@Html.DisplayFor(i => i.TotalDaysSinceRegister)</b> Tagen hast du <b>@Html.DisplayFor(i => i.TotalPokemonCatched)</b> Pokemon gefangen, davon <b>@Html.DisplayFor(i => i.TotalUniquePokemonCatched)</b> unterschiedliche. Weiter So!
<br />
<br />
Auch zu deinen Achievements lässt sich einiges sagen. Du hast bereits <b>@Html.DisplayFor(i => i.TotalAchievementsUnlocked)</b> Achievements freigeschaltet und davon <b>@Html.DisplayFor(i => i.TotalAchievementsDone)</b> bereits erfolgreich abgeschlossen.

ArenaWeb/Views/User/UserDex.cshtml
@{
    ViewData["Title"] = "UserDex";
}

<h1>UserDex</h1>